spring.application.name=transactions

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/transactions?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:transactions}
spring.datasource.password=${DB_PASSWORD:transactions}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never